### ISSUE TITLE
Create sitemap

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#11]
Sitemap generator: https://github.com/RoumenDamianoff/laravel-sitemap

It's possible we need multiple sitemaps and sitemaps index.

Sitemap generation should be a scheduled (and queued) job http://laravel.com/docs/5.1/scheduling, the right frequency should be investigated.

**Comment by kristjanjansen** [comment]
Do when #826 is done

**Comment by kkallasm** [comment]
https://support.google.com/webmasters/answer/183668

**Comment by twins16** [comment]
sitemap.org and download the code xml and paste it on the server via ftp or cpanel

**Comment by mikkpokk** [comment]
https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Generate-BIG-sitemaps

@twins16 
1) We use version control - Github (SSH connection) (no ftp / cpanel upload)
2) It's not practical to generate manually new sitemap everyday :)
