### ISSUE TITLE
Make date usage more flexible and add localization

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#12]
### Add flexibility

https://github.com/ThisVessel/Carbonated

### Add localization

Investigate https://github.com/LaravelRUS/localized-carbon and find ways to add Estonian language support. Translation files are not complex: https://github.com/LaravelRUS/localized-carbon/tree/master/src/lang/ru. If needed, create a fork of the package.

Make sure those two packages do not conflict!

**Comment by mikkpokk** [comment]
How about this?

https://github.com/jenssegers/date

**Comment by kristjanjansen** [comment]
Sounds great, need to PR an Estonian translation to them.

**Comment by kristjanjansen** [comment]
status?

**Comment by mikkpokk** [comment]
New version is out (jenssegers/date)

**Comment by kristjanjansen** [comment]
Mind to change the version number in package.json ?

**Comment by mikkpokk** [comment]
...
"jenssegers/date": "3.*@dev",
...

It's already done before
