### ISSUE TITLE
Create user friendly offline page

### ISSUE THREAD

**Issue by andreskoger** [tripikad/trip2#1234]
"Hetkel on toimumas trip.ee uuendus, külasta meid mõne hetke pärast" instead of:
<img width="1040" alt="screen shot 2016-09-18 at 12 29 02" src="https://cloud.githubusercontent.com/assets/13977200/18614655/842e1ad2-7d9b-11e6-91ea-013470c4b465.png">
Sarnane issue - https://github.com/tripikad/trip2/issues/867

**Comment by kristjanjansen** [comment]
https://laravel.com/docs/5.2/configuration#maintenance-mode

We need `resources/views/errors/503.blade.php`
