### ISSUE TITLE
Create Github organization for trip.ee

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#126]
https://github.com/tripee is gone. 

So,

https://github.com/tripeeee ?
https://github.com/tripikad ?

Discuss!

Next step would be migrating kristjanjansen/trip2 and kristjanjansen/trip2_vagrant under that organization.

**Comment by andreskoger** [comment]
võtan tripikad ära?

**Comment by kristjanjansen** [comment]
Jah
