### ISSUE TITLE
Fix and commit Fred's unread comments

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#1276]
https://github.com/tripikad/trip2/pull/1065 needs to be committed but it needs some gfx touchup

1. In https://github.com/tripikad/trip2/pull/1065/files?diff=unified#diff-bf9f9035b423b73e34928a4dfd3bd4a6R29
replace `MetaLink` component with `component('Tag')->is('red')

2. Add `Tag--red` modifier to https://github.com/tripikad/trip2/blob/master/resources/views/v2/components/Tag/Tag.css#L18

Note: the 'new comment' badge is currently only shown for administrators

**Comment by mikkpokk** [comment]
#1065
