### ISSUE TITLE
Redirect old destination routes

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#15]
### Terms

Redirect old Drupal ```/taxonomy/term/{tid}``` links to new term routes:

1. If the tid is found in is Destination model, redirect to ```/destination/{id}```

2. If the tid is found in Topic/Tag model, redirect to ``` /content/forum?tag={id}```

3. If the tid is found in Carrier model, redirect to ``` /content/flight?carrier={id}```

4. Else abort with 404

Put the whole logic to new RedirectController and move the redirect methoud from ContentController to the new controller as well.

**Comment by kkallasm** [comment]
Also  take care of 

    node/{nid}

**Comment by kkallasm** [comment]
RedirectController methods:

redirectContent(...)
redirectNode(...)
redirectTerm(...)

**Comment by kkallasm** [comment]
if ($destination = Destination::find($legacy_id)) 

   return ...

**Comment by kristjanjansen** [comment]
Closed on commit 9e09ab00baed28b615c12d1da8db1933ec3c3cef. Work based on https://github.com/tripikad/trip2/pull/49
