### ISSUE TITLE
Allow adding images to comments

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#1787]
Allow adding images to comments.

I'ts quite tricky, we do not have full-fledged wysiwyg for comments and our Editor component is an overkill for such cases.

There is a way though to combine and extend couple of exisiting components:

https://github.com/tripikad/trip2/blob/master/resources/views/components/EditorSmall/EditorSmall.vue

is a simple wrapper around Quill editor that is a simple wrapper around `contenteditable`. 

So you can copy EditorSmall into CommentEditor.vue and start working from there

#### Images can be added:

by launching imagepicker from EditorSmall toolbar: 

```js
this.$events.$emit('imagepicker.show', this.target)
// target is id to identify as a receiver, like 'comment'
```

You will need to extend the `imagepicker.show` parameters to receive user = true/fase parameter and also add additional ajax endpoint to show only images uploaded by current user.

#### Images can be received:

```js
this.$events.$on('imagepicker.insert', payload => {
    if (payload.target === this.target) {
        this.insertImage(payload.id)
    }
    this.$events.$emit('imagepicker.hide')
})
```

You need to extend the `imagepicker.insert` payload object to contain also the image url since we need to show the real image in the Quill/contenteditable area

**Comment by mikkpokk** [comment]
Praegu sai lisatud pildi lisamise võimalus läbi URL-i. Kardan, et kui kõikidel foorumlastel meie serverisse pilte lasta salvestada siis purk saab väga kiirelt juba täis. #1806
