### ISSUE TITLE
Show view counters in comments

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#1788]
From shortlist https://docs.google.com/spreadsheets/d/1nlAIo9h5sQ0NoGzJFc7cFcN-xrf0hcKiWMtEgoHFsiA/edit#gid=0

> Seal ma ka ei oska palju inputti anda. me teeme juba nii palju INSERTe posituste vaatamisel :)
 et enam vist vahet ple kui sa iga vaatamisega veel midagi lehele kirjutad... aga view countereid yldiselt tehakse ikkagi redisega vms

**Comment by mikkpokk** [comment]
#1802
