### ISSUE TITLE
Bring pack comment paging

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#1789]
From shortlist https://docs.google.com/spreadsheets/d/1nlAIo9h5sQ0NoGzJFc7cFcN-xrf0hcKiWMtEgoHFsiA/edit#gid=0

Lets go for full PHP for now

> hea kui mikk leiaks viisi mitte polluteda commentite URLe page parameetriga vaid teha see kuidagi maagiliselt

**Comment by mikkpokk** [comment]
#1802
