### ISSUE TITLE
Foorumi testid vajavad uut lähenemist

### ISSUE THREAD

**Issue by mikkpokk** [tripikad/trip2#1808]
![image](https://user-images.githubusercontent.com/14272312/37247657-3626bf18-24c7-11e8-901f-d07cce5a9589.png)

Tänu foorumis kasutavale editorile ja vue maagiale ei tuvasta BrowserKit mitte kuidagi <textarea></textarea> elementi kuigi see tegelikult isegi browseris eksisteerib (display: none elemendi sees). 

Outputides BrowserKiti  kätte saadud HTML-koodi siis see kood on vue-koodi täis, kuid vastavat elementi tõesti ei eksisteeri.

BrowserKit ouput:
![image](https://user-images.githubusercontent.com/14272312/37247714-439df430-24c8-11e8-9d5d-d8e52cfef4ff.png)

CMD+F:
`name="body"`
`name='body'`

Veateade: InvalidArgumentException: Nothing matched the filter [body] CSS query provided for [http://localhost/forum/create/forum].

Käsitsi testides kõik toimib, kuid tuleviku mõttes tasuks nende testidega midagi välja mõelda.

**Comment by kristjanjansen** [comment]
Closed by #1833 , more work to be done
