### ISSUE TITLE
Set up Google Custom Search account

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#185]
We have one already but its set up under kristjan.jansen@gmail.com

Make a new one

https://support.google.com/customsearch/answer/2630963?hl=en

**Comment by andreskoger** [comment]
Uus konto tehtud, tahavad seda saada tripi lehele:
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67792699-1', 'auto');
  ga('send', 'pageview');

</script>

Konto olemas, ligipääs tagatud hetkel kikale ja kasparile

**Comment by andreskoger** [comment]
scripti tahavad lehele saada, aga ei lase siia kopida

**Comment by kristjanjansen** [comment]
Its done https://cse.google.com/cse/all
