### ISSUE TITLE
Redirect too long legacy content aliases

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#32]
There are set of aliases that are currently not captured by the *.html regexp. They look like this:

nid: 55956
    
    content/euroopa/hispaania/hispaania-kel-on-soovi-hispaania-elu-minna-nautima-ehk-siis-elama-ja-toole

nid: 55966
      
    content/tere-ja-kes-on-minuga-alates-1-detsembrist-uhinema-minuga-reisile-laeva-kruiisile-miami-flor

The URL length are around 100 to 102 so they can be be captured using ```{100,}```

**Comment by mikkpokk** [comment]
@kristjanjansen I don't get it.

All those slugs ("sliced" aliases, *.html-0, *.html) exists in trip database but not exist in trip2 database because sql not found specific node id from new content (because we don't use full convert while we are developing?).
