### ISSUE TITLE
What is the proper way to include standalone SVGs to the page?

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#338]
Icons have their component.icon but what about standalone SVGs (logo, map etc)

should we just go for img tag?

**Comment by mikkpokk** [comment]
sprites = component
standalones = independent cases

Right?

So in my opinion img tag sounds simple and logical in this case.

**Comment by apani** [comment]
What if there is a need to edit the "fill" property in css for example? One can not do that using the "img" tag. I'd recommend using the full svg ...The question remains ...
