### ISSUE TITLE
Create favicons

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#350]
1. Haiku: Save master favicon to ```/resources/svg/favicon/favicon.svg``` (around 512x512 px) 

2. Create Follow-up issue to generate all neccessary favicons using

https://www.npmjs.com/package/gulp-svg2png
https://github.com/haydenbleasel/gulp-favicons

**Comment by apani** [comment]
https://github.com/tripikad/trip2/pull/383
