### ISSUE TITLE
Unify list and row component

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#358]
Differences:

list component accepts array of items, row component is meant for single item rendering. Was the case for having an list as interating component just the ```ul``` wrapper?

As the use case for list is quite complex I'd suggest to move away from ```ul li``` semantics and go for HTML5 ````article``` and/or ```section``` so the need for ```ul``` wrapper goes away and component will accept just a single item. Also, it works well with Blade's ```@each('view.name', $items, 'item', 'view.empty')```, see http://laravel.com/docs/5.1/blade#control-structures

Also note that ```$extra``` is no longer neccessary

**Comment by apani** [comment]
We still need something for lists, so maybe keep the list component simple and use it to display plain lists (single line texts / links - input should be route, title, modifier) and use row component for something more than a list component could provide?

**Comment by kristjanjansen** [comment]
Yep, lets keep both list and row

**Comment by apani** [comment]
https://github.com/tripikad/trip2/pull/361
