### ISSUE TITLE
Unify new header / masthead and old header[1-3] components

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#360]
Currently we have some old header sections that we need to incorporate to new header / mastehead components:

    @yield('header1.left') // not used
    @yield('header1.top') // user edit / show pages for avatar
    @yield('header1.bottom') // user show, "joined x ago"
    @yield('header1.right') // in many content pages, used for "Add contenttype" button

    @yield('header2.content') // used either for in-page menu or filter(s)
    @yield('header3.content') // used for filter(s)

So we need:

- a custom header for user pages
- a place for "Add contenttype" button in header / mastehead
- a place for menus in header / mastehead
- a place for filter(s)  in header / mastehead

**Comment by apani** [comment]
Needs some design input
