### ISSUE TITLE
Upgrade info/error and info/success components

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#375]
Previously we relied on ```.alert``` / ```.alert-danger``` / ```.alert-success``` classes from Bootstrap. Replace it with a custom styling (```_info.scss?```) that supports ```m-red``` and ```m-green``` modifiers (perhaps our full palette)?

Note also that we have a naming clash with destination/info component. Consider renaming the ```info``` thing with ```alert``` everywhere.

**Comment by apani** [comment]
https://github.com/tripikad/trip2/pull/384 - I'll leave the renaming part to someone else - *alert/error* and *alert/success* would be ideal

**Comment by mikkpokk** [comment]
What renaming thing we are talking about now? Only info "things" in destination/info component are c-destination-**info**... @apani @kristjanjansen
