### ISSUE TITLE
Decide what to do with legacy travel offers

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#605]
We have legacy travel offers but the new travel offer system will be not ready for V1

### Option A: Keep the old Drupal site running displaying only the legacy travel offers

- Needs to move to http://vana.trip.ee
- Needs a top ribbon to the old site explaining the situation
- Needs enabling https://www.drupal.org/project/login_disable to disable logging to old site except the commercial clients
- Needs to clear all user sessions
- Additional overhead for customer support
- Needs to compile a list of e-mail of commercial clients and end out mass email to commercial clients explaining the situation
- Additional ```$40/month``` overhead to keep old server running
- Its a high price for such a underused machine but it's very complicated to [downgrade](https://www.linode.com/docs/migrate-to-linode/disk-images/resizing-a-linode) this Linode machine since old Drupal site disk usage is quite high:

        Current disk size: 98G
        Current usage: 68G

  Possible Linode plans to downgrade:

        1GB plan disk size: 24G
        2GB plan disk size: 48G

### Option B: Do not display legacy travel offers

- Losing trust with clients since our new travel offer solution will be rolled out in V2
- No legacy site tinkering
- No server cost overhead
- No tricky user session issues

**Comment by andreskoger** [comment]
Trip Travel offers will not be shown in V1. All the data from there can be deleted if necessary.
