### ISSUE TITLE
Decide e-mail provider

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#606]
Re-surfacing the old issue #98 

### Option A: Mandrill

**Free plan:**

hourly quota: 25 mails
2,000 email credits

**Paid plan:** ```9.95$/month```

mails per month: 25000 (833 per day)
paid hourly quota: more than 25 mails / h, details unknown

DNS verification can help ratings but is not needed https://mandrill.zendesk.com/hc/en-us/articles/205582267-What-are-SPF-and-DKIM-and-how-do-I-set-them-up-

When we also use Mailchimp, we can take advantage of bundled pricing:https://mandrill.zendesk.com/hc/en-us/articles/205582857-What-is-MailChimp-bundled-pricing-

### Option B: Mailgun

Free plan:

10000 emails per month (333 per day)
300 emails per day if not verified sender. Verifying needs some DNS mangling but seems to be free https://documentation.mailgun.com/quickstart-sending.html#verify-your-domain
Data retention for logs and the Events API is 2 days.
The limit for number of domains is 5.

Paid plan:

```?$/month```, depends how much you go past 10000 per month
no email limits
Data retention for Logs and the Events API is 30 days.

DNS setup is somewhat complex

### Option C: CampaignMonitor

2500 mails per month (83 per day) for ```$9```
unlimited for ```$29```

See also https://laracasts.com/lessons/transactional-emails-with-campaign-monitor-in-laravel

**Comment by andreskoger** [comment]
Option A

Account to MailChimp and Mandrill for Trip.ee done. Connected Mandrill to MailChimp. Next step to verify DKIM Settings&SPF Settings - How ?

**Comment by kristjanjansen** [comment]
Closing this old thread, continue discussion in #644
