### ISSUE TITLE
Decide ad provider

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#607]
### Option A: Google Doubleclick for Publishers (small business)

Just go for http://www.google.com/dfp and set up a account and add a staging setup with sample ads.

### Option B: ???

**Comment by andreskoger** [comment]
DoubleClick kuvab mingite ettevõtete reklaami ning seal on vähe (kui üldse) reisiteemalist saadaval. Mikuga arutasime ning Mikk lubas teha mingi mooduli, millega  saab bännerid keskkonda üles ning statistika läbi google kätte.

**Comment by kristjanjansen** [comment]
Still, lets test Google DFB for starters, we can have our own creatives only

**Comment by kristjanjansen** [comment]
Closing with decision: Google DFB for now, lets revisit in V2
