### ISSUE TITLE
Add cron entry

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#638]
Add crontab entry to https://github.com/tripikad/trip2_vagrant/blob/master/provision.sh

See
https://laravel.com/docs/5.2/scheduling#introduction
http://stackoverflow.com/questions/4880290/how-do-i-create-a-crontab-through-a-script/9625233#9625233

**Comment by kristjanjansen** [comment]
Waiting for a PR against provision.sh. Note that different environments need different entries - laravel root dir is different

**Comment by kkallasm** [comment]
provision will write it to crontab but it's not showing up in server

**Comment by kristjanjansen** [comment]
Closed by tripikad/trip2_vagrant#38
