### ISSUE TITLE
Send simple data to Google Analytics

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#684]
The minimum amount of data we need to send to Google Analytics:

```php
use Auth;

if (Auth::check()) {
    Analytics::setUserId(Auth::user()->id);
    Analytics::trackCustom("ga('set', 'user_role', Auth::user()->role);");
}
```

(can be set on ```app/Providers/AppServiceProvider::boot()```)

See also

https://github.com/ipunkt/laravel-analytics
https://css-tricks.com/learning-use-google-analytics-effectively-codepen/

**Comment by kristjanjansen** [comment]
Reopening, do not see the data in GA side

**Comment by mikkpokk** [comment]
Because GA is not connected yet
