### ISSUE TITLE
Resolve HTML allowed tags and CKEditor conflict

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#690]
When introducing CKEditor, we allowed admin users to use wide range of HTML tags that we tend to use filter out on content input and output:

https://github.com/tripikad/trip2/blob/master/config/site.php#L7 

Figure out a proper solution to this:

**Option A:** Limit CKEditor functionality and map all the toolbar buttons to the allowed tags

**Option B:** Do not filter the content types that are edited with CKEditor

Note the related tests need to reflect it #229

**Comment by mikkpokk** [comment]
Option B
