### ISSUE TITLE
Clean up profile view and edit pages

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#703]
### Profile view

- Likes: update to live data ```$user->flags->*somefilters*->count() ```
- Hide user location icon
- Tab bar:
```
[Profiil][Sõnumid][Jälgmised]     [Muuda profiili][Lisa riigid kus olen käinud]
```
- Hide Star/followers (no backend)
- Rename "Tegevuste ajalugu" -> "Viimased postitused" 
- Rename "Üldine" -> "Üldfoorum"

### Profile edit

- Remove "Praegune asukoht" (no backend)
- Remove "Skype" field
- Bring back "Twitter" field
- Remove "Taustapilt" (no backend)
- Remove "Profiili värv" (no backend)

**Comment by mikkpokk** [comment]
#678
