### ISSUE TITLE
Add back pink background for unpublished comments

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#820]

**Comment by mikkpokk** [comment]
@kristjanjansen Rohkem detaile palun, pole näinud milline see varem oli.

**Comment by kristjanjansen** [comment]
@mikkpokk 

Lisa forum postidele / commentitele modifierklass ```m-unpublished``` ja stiliseeri see

```css
background-color: #ffb6c1;
opacity: 0.7:
```
