### ISSUE TITLE
Remove duplicate topics and destinations

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#823]
Is it a double convert issue?

![valdkonnad_dropdown_topelt](https://cloud.githubusercontent.com/assets/241603/15668341/6f1bfc3c-2723-11e6-8e99-f711613155c2.jpg)

**Comment by mikkpokk** [comment]
Double convert it is

**Comment by mikkpokk** [comment]
@kristjanjansen I don't have access to main database to solve the problem or should I do "hardcode" fix?

**Comment by kristjanjansen** [comment]
Topics: just keep one from the dupes and re-assign content

```
>>> \App\Topic::whereIn('id', function ($query) { $query->select('id')->from('topics')->groupBy('name')->havingRaw('count(*) > 1'); })->get();
=> Illuminate\Database\Eloquent\Collection {#977
     all: [
       App\Topic {#978
         id: 704,
         name: "Reisiraamatud",
       },
       App\Topic {#979
         id: 716,
         name: "Varustus",
       },
       App\Topic {#980
         id: 764,
         name: "Majutus ja hotellid",
       },
       App\Topic {#981
         id: 4427,
         name: "Turvalisus",
       },
     ],
   }
>>> 
```

Destinations:

>>> \App\Destination::whereIn('id', function ($query) { $query->select('id')->from('destinations')->groupBy('name')->havingRaw('count(*) > 1'); })->get();
=> Baum\Extensions\Eloquent\Collection {#966
     all: [
       App\Destination {#968
         id: 456,
         name: "Gibraltar",
         parent_id: 318,
         lft: 589,
         rgt: 590,
         depth: 2,
         slug: "gibraltar",
       },
     ],
   }

merge the dupe gibraltar (id 2395) with this and reassign content
