### ISSUE TITLE
Add human readable slugs to content

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#826]
```
content/forum/90627
```

becomes

```
/cherry-pakkumine-kuprosele-90627
```

or something

See also:

https://laravel.com/api/5.2/Illuminate/Support/Str.html#method_ascii
http://packalyst.com/packages/tag/slug
https://laracasts.com/lessons/unique-slugs-in-laravel

**Comment by kristjanjansen** [comment]
Mikk:

* Slugid eraldi tabelis (koos relation id ja relation type’iga)
* Laravel Slugify aitab teha pealkirja automaatselt slugiks
* Edaspidi eraldi slugi field ehk nähtavale tuua ka tripis? Mul toimib pealkirja sisestamisel slugi autocomplete ja vajadusel saab hiljem muuta
* helper juurde, mis lisab olemasoleva slugi puhul automaatselt järjekorra nr (minu-reisiidee -> minu-reisiidee-2, minu-reisiidee-3 jne)

**Comment by kristjanjansen** [comment]
#1031

**Comment by kkallasm** [comment]
should work now
@see #1031
