### ISSUE TITLE
Refresh user profile image

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#853]
When user profile image component shows the image of the logged in user, add a small hash to the image filename, ```"?".str_random(4)``` so when the user changes its image, its instantly refreshed.

Not critical, feel free to push to V2

**Comment by mikkpokk** [comment]
Läheb praegu ainult navbar.user komponenti (user.edit all olemas). Kui paneks profile komponendi alla tähendaks see seda, et kunagi pilte ei cache'ita - kannatab kasutaja laadimisaeg.
