### ISSUE TITLE
Profile pictures turn into ovals on IE/Edge

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#861]
![ovaalid](https://cloud.githubusercontent.com/assets/241603/15707939/230424e6-2804-11e6-9ffd-73aaf539942c.jpg)

> Edge ja IE11 teevad midagi kummalist nende kommentaari juures olevate kasutajate pisipiltidega (http://46.101.120.198/…/forum/94753 näiteks), need muutuvad ovaalseteks. Näide siin Seejuures foorumi avalehel (http://46.101.120.198/content/forum) on need pildid korras. Chromega on need pildid kõikjal OK.

**Comment by mikkpokk** [comment]
@apani Viska pilk peale

**Comment by apani** [comment]
made a pull request for this
