### ISSUE TITLE
Adding photos is complicated via drag-and-drop in photo creation form

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#865]
Its hard to figure out correct order of actions to make file upload work in photo upload dialog.

<img width="530" alt="screen shot 2016-06-01 at 12 04 04" src="https://cloud.githubusercontent.com/assets/241603/15769892/f5cbf76e-2967-11e6-8a31-217d0744408c.png">

**Comment by mikkpokk** [comment]
@kristjanjansen Mis lahendus oleks? Karm oleks faili serverisse ka lasta sellel hetkel kui vorm ei valideeru veel. Tulevikus plaan anyway formid ajaxi peale teha (eesmärgiga, et hakkab piltide lisamine ka lõpuks mõistlikumalt toimima)

**Comment by kristjanjansen** [comment]
See also #881
