### ISSUE TITLE
new 404 page

### ISSUE THREAD

**Issue by andreskoger** [tripikad/trip2#867]
Make new 404 page. Design attached.

![trip-404](https://cloud.githubusercontent.com/assets/13977200/15773311/e951855a-297e-11e6-8452-37f6be2e1456.png)

**Comment by kristjanjansen** [comment]
Can easily implented via cusco:

2col layout with:

header:
* component/HeaderLight

content:
* component/Title
* component/Body

sidebar:
regions/About (does not exist yet but we need it in many places)
