### ISSUE TITLE
Bring back e-mail sending for followed content

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#894]
- Uncomment code in `CommentController`
- Show the setting in profile edit page
- Test, test, test
- Launch
- Profit!

**Comment by mikkpokk** [comment]
#1694

**Comment by mikkpokk** [comment]
Implement that part to V2CommentController

`use App\Mail\NewCommentFollow;`

`$follower_emails = $comment->content->followersEmails()->forget(Auth::user()->id)->toArray();
if ($follower_emails) {
    foreach ($follower_emails as $follower_id => &$follower_email)
    {
        Mail::to($follower_email)->queue(new NewCommentFollow($follower_id, $comment));
    }
}`

**Comment by mikkpokk** [comment]
#1674

**Comment by mikkpokk** [comment]
#1695 closes the issue
