### ISSUE TITLE
Static content display does not honor newlines

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#901]
![Uploading Screen Shot 2016-06-13 at 22.49.57.png…]()

**Comment by mikkpokk** [comment]
<img width="1303" alt="1465853720" src="https://cloud.githubusercontent.com/assets/14272312/16023957/fa09eff8-31c7-11e6-8779-4a02b45e0662.png">

@kristjanjansen Demoserveri converdi jama?
