### ISSUE TITLE
Kill forum post pager

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#904]
Just let it all flow

**Comment by mikkpokk** [comment]
@kristjanjansen

Andres: "uuh, see on halb sest siis on niipalju tühja seal parempoolsel küljel"

Mina - see toob kaasa ka aeglase laadimise (veel enam kui keegi kasutab kuskil avalikku internetti + muidugi MySQL ei saa meil siis pikemate foorumi teemade all nii pea closeda kasutaja sessioni - praktikas pika peale jookseb SQL kokku ja tahab tabeli "restarti").

Hetkel suurendasin, et ühel lehel kuvatakse 35 kommentaari ja nüüd on paginator nii üleval kui ka all.

Edaspidi ehk mõelda välja mingisugune lazyload lahendus?
