### ISSUE TITLE
Add head tag descriptions

### ISSUE THREAD

**Issue by andreskoger** [tripikad/trip2#911]
### 1. In ```layouts.main``` replace

```html
<meta property="og:description" content="@yield('description')">
```

with more generic

```html
<meta name="description" content="@yield('description')">
<meta property="og:description" content="@yield('description')">
<meta name="twitter:description" content="@yield('description')">
```

### 2. Assign descriptions sections in views:

|View|description|
|---|---|
|content.flights.index|```trans('site.description.flights')```|
|content.flights.show|```str_limit(strip_tags($content->body), 200)```|
|content.news.index|```trans('site.description.news')```|
|content.news.show|```str_limit(strip_tags($content->body), 200)```
|content.travelmate.index|```trans('site.description.travelmate')```|
|content.travelmate.show|```str_limit(strip_tags($content->body), 200)```|
|content.forum.index|```trans('site.description.forum')```|
|content.forum.show|```str_limit(strip_tags($content->body), 200)```|
|All others|```trans('site.description')```|

### 1. In ```layouts.main``` add

```
<meta property="og:image" content="@yield('head_image')">
<meta name="twitter:image" content="@yield('head_image')">
```

### 2. Assign descriptions sections in views:

|View|description|
|---|---|
|content.flights.show|Whatever image is in the masthead in this page but ```medium``` image preset|
|content.news.show|Whatever image is in the masthead in this page but ```medium``` image preset|
|content.photo.show|Whatever image is on the page but with ```medium``` image preset|
|All others|@andreskoger, make your flatmake work|

### 3. Profit!

See also

https://github.com/joshbuchea/HEAD/blob/master/README.md
https://developers.facebook.com/docs/sharing/webmasters#images
https://css-tricks.com/essential-meta-tags-social-media/

**Comment by kristjanjansen** [comment]
@mikk, @kkallasm - who takes it?
