### ISSUE TITLE
Add head tag images

### ISSUE THREAD

**Issue by andreskoger** [tripikad/trip2#912]
### 1. In ```layouts.main``` add

```
<meta property="og:image" content="@yield('head_image')">
<meta name="twitter:image" content="@yield('head_image')">
```

### 2. Assign descriptions sections in views:

|View|description|
|---|---|
|content.flights.show|Whatever image is in the masthead in this page but ```medium``` image preset|
|content.news.show|Whatever image is in the masthead in this page but ```medium``` image preset|
|content.photo.show|Whatever image is on the page but with ```medium``` image preset|
|All others|@andreskoger, make your flatmake work|

### 3. Profit!

See also

https://github.com/joshbuchea/HEAD/blob/master/README.md
https://developers.facebook.com/docs/sharing/webmasters#images

**Comment by kristjanjansen** [comment]
Merged to #911
