### ISSUE TITLE
Choose a e-mail provider

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#98]
In order to get good service and statistics we need to pick between

https://www.mandrill.com and http://www.mailgun.com

Find out their differences -- pricing, rate limits, features etc

**Comment by kristjanjansen** [comment]
Mandrill: 

free plan:
hourly quota: 25 mails
 2,000 email credits

paid plan: 9.95$/mm
mails per month: 25000 (833 per day)
paid hourly quota: more than 25 mails / h, details unknown
limit on recipients in cc / bcc: unknown

**Comment by kristjanjansen** [comment]
Mailgun:

free plan:
10000 emails per month
300 emails per day if not verified sender. Verifying needs some DNS mangling but seems to be free https://documentation.mailgun.com/quickstart-sending.html#verify-your-domain

**Comment by kristjanjansen** [comment]
Mailgun seems to be a better option but has more complex setup (DNS stuff)

**Comment by kristjanjansen** [comment]
Andres will create demo accounts

**Comment by kristjanjansen** [comment]
If we use mailvhimp there is bundled pricing https://mandrill.zendesk.com/hc/en-us/articles/205582857-What-is-MailChimp-bundled-pricing-

**Comment by kristjanjansen** [comment]
There is also CampaignMonitor option https://laracasts.com/lessons/transactional-emails-with-campaign-monitor-in-laravel

**Comment by andreskoger** [comment]
http://www.pcmag.com/article2/0,2817,2453354,00.asp

Otsustasin MailChimpi kasuks. Kutsed nii kikale kui kasparile teele pandud
